feat(deploy): Update workflow for collage deployment and adjust environment configurations

diff --git a/.github/workflows/collage.yml b/.github/workflows/collage.yml
--- a/.github/workflows/collage.yml
+++ b/.github/workflows/collage.yml
@@ -1,21 +1,16 @@
 name: Deploy College to VPS
 
 on:
-  push:
-    branches: [ "main" ]
+  workflow_run:
+    workflows: ["Deploy to VPS"]
+    types:
+      - completed
+    branches: ["main"]
 
 jobs:
-  wait:
-    runs-on: self-hosted
-    steps:
-      - name: Wait for 10 minutes
-        run: |
-          echo "Waiting for 10 minutes to ensure main site deployment is complete..."
-          sleep 600
-
   deploy:
-    needs: wait
     runs-on: self-hosted
+    if: ${{ github.event.workflow_run.conclusion == 'success' }}
 
     steps:
     - name: Set up Node.js
@@ -24,29 +19,29 @@ jobs:
         node-version: '22.7.0'
 
     - name: Set up environment variables
-      working-directory: /var/www/college.devtrend.tech
+      working-directory: /var/www/collage.devtrend.tech
       run: |
-        echo "CURRENT_RELEASE=$(readlink .next-college)" >> $GITHUB_ENV
+        echo "CURRENT_RELEASE=$(readlink .next-collage)" >> $GITHUB_ENV
         echo "NEW_BUILD_DIR=releases/$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
         # add HOME as /root to fix npm permission issue
         echo "HOME=/root" >> $GITHUB_ENV
 
     - name: Fetch the latest changes
-      working-directory: /var/www/college.devtrend.tech
+      working-directory: /var/www/collage.devtrend.tech
       run: |
         echo -e ">>> \033[1;34mFetching the latest changes...\033[0m"
         git fetch origin main || { echo -e "\033[1;31mFailed to fetch the latest changes\033[0m"; exit 1; }
         echo -e "\033[1;32mLatest changes fetched successfully\033[0m"
 
     - name: Reset to Main branch
-      working-directory: /var/www/college.devtrend.tech
+      working-directory: /var/www/collage.devtrend.tech
       run: |
         echo -e ">>> \033[1;34mResetting to main branch...\033[0m"
         git reset --hard origin/main || { echo -e "\033[1;31mFailed to reset to main branch\033[0m"; exit 1; }
         echo -e "\033[1;32mReset to main branch successfully\033[0m" 
 
     - name: Clean up old temp directory if exists
-      working-directory: /var/www/college.devtrend.tech
+      working-directory: /var/www/collage.devtrend.tech
       run: |
         if [ -d "temp" ]; then
           echo -e ">>> \033[1;34mCleaning up old temp directory...\033[0m"
@@ -54,27 +49,27 @@ jobs:
         fi
 
     - name: Install dependencies
-      working-directory: /var/www/college.devtrend.tech
+      working-directory: /var/www/collage.devtrend.tech
       run: |
         echo -e ">>> \033[1;34mInstalling dependencies...\033[0m"
         npm install || { echo -e "\033[1;31mFailed to install dependencies\033[0m"; exit 1; }
         echo -e "\033[1;32mDependencies installed successfully\033[0m"
 
     - name: Generate Prisma Client for College
-      working-directory: /var/www/college.devtrend.tech
+      working-directory: /var/www/collage.devtrend.tech
       run: |
         echo -e ">>> \033[1;34mGenerating Prisma Client for College...\033[0m"
-        npm run postinstall:college || { echo -e "\033[1;31mFailed to generate Prisma Client\033[0m"; exit 1; }
+        npm run postinstall:collage || { echo -e "\033[1;31mFailed to generate Prisma Client\033[0m"; exit 1; }
         echo -e "\033[1;32mPrisma Client generated successfully\033[0m"
 
     - name: Build the project in temp directory
-      working-directory: /var/www/college.devtrend.tech
+      working-directory: /var/www/collage.devtrend.tech
       run: |
-        echo -e ">>> \033[1;34mBuilding the college site...\033[0m"
-        BUILD_DIR=temp npm run build:college || { echo -e "\033[1;31mBuild failed\033[0m"; exit 1; }
+        echo -e ">>> \033[1;34mBuilding the collage site...\033[0m"
+        BUILD_DIR=temp npm run build:collage || { echo -e "\033[1;31mBuild failed\033[0m"; exit 1; }
 
     - name: Check if temp directory exists
-      working-directory: /var/www/college.devtrend.tech
+      working-directory: /var/www/collage.devtrend.tech
       run: |
         if [ ! -d "temp" ]; then
           echo -e "\033[1;31mtemp Directory not exists!\033[0m"
@@ -83,7 +78,7 @@ jobs:
         echo -e "\033[1;32mBuild successful in temp directory\033[0m"
 
     - name: Create release directory if not exists
-      working-directory: /var/www/college.devtrend.tech
+      working-directory: /var/www/collage.devtrend.tech
       run: |
         echo -e ">>> \033[1;34mCreating release directory if not exists...\033[0m"
         if [ ! -d "releases" ]; then
@@ -91,36 +86,36 @@ jobs:
         fi
 
     - name: Move the build to releases directory with timestamp
-      working-directory: /var/www/college.devtrend.tech
+      working-directory: /var/www/collage.devtrend.tech
       run: |
         echo -e ">>> \033[1;34mMoving build to releases directory...\033[0m"
         mv temp "$NEW_BUILD_DIR" || { echo -e "\033[1;31mFailed to move build to releases directory\033[0m"; exit 1; }
         echo -e "\033[1;32mBuild moved to $NEW_BUILD_DIR\033[0m"
 
     - name: Update the symbolic link
-      working-directory: /var/www/college.devtrend.tech
+      working-directory: /var/www/collage.devtrend.tech
       run: |
         echo -e ">>> \033[1;34mUpdating symbolic link...\033[0m"
-        ln -sfn "$NEW_BUILD_DIR" .next-college || { 
+        ln -sfn "$NEW_BUILD_DIR" .next-collage || { 
           echo -e "\033[1;31mFailed to update symbolic link\033[0m"; 
-          ln -sfn "$CURRENT_RELEASE" .next-college  # Revert to the old release
+          ln -sfn "$CURRENT_RELEASE" .next-collage  # Revert to the old release
           exit 1; 
         }
         echo -e "\033[1;32mRelease $NEW_BUILD_DIR staged successfully\033[0m"
 
     - name: Reload the pm2 process
-      working-directory: /var/www/college.devtrend.tech
+      working-directory: /var/www/collage.devtrend.tech
       run: |
         echo -e ">>> \033[1;34mReloading the pm2 process...\033[0m"
-        pm2 reload college-devtrend-tech --update-env || { 
+        pm2 reload collage-devtrend-tech --update-env || { 
           echo -e "\033[1;31mFailed to reload pm2 process\033[0m"; 
-          ln -sfn "$CURRENT_RELEASE" .next-college  # Revert to the old release
+          ln -sfn "$CURRENT_RELEASE" .next-collage  # Revert to the old release
           exit 1; 
         }
         echo -e "\033[1;32mPM2 process reloaded successfully\033[0m"
 
     - name: Check the number of releases and keep only 3 latest releases
-      working-directory: /var/www/college.devtrend.tech
+      working-directory: /var/www/collage.devtrend.tech
       run: |
         RELEASES_COUNT=$(find releases -mindepth 1 -maxdepth 1 -type d | wc -l)
         if [ "$RELEASES_COUNT" -gt 3 ]; then
