fix: Refactor deployment workflow to improve environment setup, streamline build process, and enhance symbolic link management

diff --git a/.github/workflows/collage.yml b/.github/workflows/collage.yml
--- a/.github/workflows/collage.yml
+++ b/.github/workflows/collage.yml
@@ -1,156 +1,123 @@
-name: Deploy Collage to VPS
+name: Deploy to Collage VPS
 
 on:
-  workflow_run:
-    workflows: ["Deploy to VPS"]
-    types:
-      - completed
-    branches: ["main"]
+  push:
+    branches: [ "main" ]
 
 jobs:
   deploy:
-    runs-on: self-hosted
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
+    environment: production
+    runs-on: ubuntu-latest
+    env:
+      DATABASE_URL: ${{ secrets.DATABASE_URL }}
+      MAILGUN_USER: ${{ secrets.MAILGUN_USER }}
+      MAILGUN_PASS: ${{ secrets.MAILGUN_PASS }}
+      NEXT_PUBLIC_REMOTE_URL: ${{ vars.NEXT_PUBLIC_REMOTE_URL }}
+      NEXT_PUBLIC_BASE_URL: ${{ vars.NEXT_PUBLIC_BASE_URL }}
+      NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
+      SECRET_KEY: ${{ secrets.SECRET_KEY }}
+      CONTENT_GENERATOR_API_LINK: ${{ vars.CONTENT_GENERATOR_API_LINK }}
+      NEXT_PUBLIC_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_MEASUREMENT_ID }}
+      PORT: ${{ vars.PORT }}
+      WEBSITE_TYPE: ${{ vars.WEBSITE_TYPE }}
 
     steps:
-      
+    - name: Check out the repository
+      uses: actions/checkout@v3
+
     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
         node-version: '22.7.0'
 
     - name: Set up environment variables
-      working-directory: /var/www/collage.devtrend.tech
       run: |
-        echo "CURRENT_RELEASE=$(readlink .next)" >> $GITHUB_ENV
         echo "NEW_BUILD_DIR=releases/$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
         echo "PORT=3050" >> $GITHUB_ENV
-        echo "HOME=/root" >> $GITHUB_ENV
 
     - name: Fetch the latest changes
-      working-directory: /var/www/collage.devtrend.tech
-      run: |
-        echo -e ">>> \033[1;34mFetching the latest changes...\033[0m"
-        git fetch origin main || { echo -e "\033[1;31mFailed to fetch the latest changes\033[0m"; exit 1; }
-        echo -e "\033[1;32mLatest changes fetched successfully\033[0m"
+      run: git fetch origin main
 
     - name: Reset to Main branch
-      working-directory: /var/www/collage.devtrend.tech
-      run: |
-        echo -e ">>> \033[1;34mResetting to main branch...\033[0m"
-        git reset --hard origin/main || { echo -e "\033[1;31mFailed to reset to main branch\033[0m"; exit 1; }
-        echo -e "\033[1;32mReset to main branch successfully\033[0m" 
+      run: git reset --hard origin/main
 
     - name: Clean up old temp directory if exists
-      working-directory: /var/www/collage.devtrend.tech
       run: |
         if [ -d "temp" ]; then
-          echo -e ">>> \033[1;34mCleaning up old temp directory...\033[0m"
           rm -rf temp
         fi
-
-    - name: Cache Node.js modules
-      uses: actions/cache@v3
-      with:
-        path: ~/.npm
-        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-        restore-keys: |
-          ${{ runner.os }}-node-
 
     - name: Install dependencies
-      working-directory: /var/www/collage.devtrend.tech
       run: |
-        echo -e ">>> \033[1;34mInstalling dependencies...\033[0m"
-        npm ci || { echo -e "\033[1;31mFailed to install dependencies\033[0m"; exit 1; }
-        echo -e "\033[1;32mDependencies installed successfully\033[0m"
-
-    - name: Generate Prisma Client for Collage
-      working-directory: /var/www/collage.devtrend.tech
-      run: |
-        echo -e ">>> \033[1;34mGenerating Prisma Client for Collage...\033[0m"
-        npm run postinstall || { echo -e "\033[1;31mFailed to generate Prisma Client\033[0m"; exit 1; }
-        echo -e "\033[1;32mPrisma Client generated successfully\033[0m"
+        npm ci
 
     - name: Build the project in temp directory
-      working-directory: /var/www/collage.devtrend.tech
       run: |
-        echo -e ">>> \033[1;34mBuilding the project...\033[0m"
-        # Create temp directory if it doesn't exist
         mkdir -p temp
-        # Set BUILD_DIR and PORT environment variables
-        BUILD_DIR=temp PORT=5001 npm run build || { 
-          echo -e "\033[1;31mBuild failed\033[0m"
-          rm -rf temp
-          exit 1
-        }
-        echo -e "\033[1;32mBuild completed successfully\033[0m"
+        BUILD_DIR=temp npm run build
 
     - name: Verify build output
-      working-directory: /var/www/collage.devtrend.tech
       run: |
-        if [ ! -d "temp" ] ; then
-          echo -e "\033[1;31mBuild output is invalid!\033[0m"
+        if [ ! -d "temp" ]; then
           exit 1
         fi
-        echo -e "\033[1;32mBuild output verified\033[0m"
 
     - name: Create release directory if not exists
-      working-directory: /var/www/collage.devtrend.tech
       run: |
-        echo -e ">>> \033[1;34mCreating release directory if not exists...\033[0m"
         if [ ! -d "releases" ]; then
           mkdir releases
         fi
 
     - name: Move the build to releases directory with timestamp
-      working-directory: /var/www/collage.devtrend.tech
-      run: |
-        echo -e ">>> \033[1;34mMoving build to releases directory...\033[0m"
-        mv temp "$NEW_BUILD_DIR" || { echo -e "\033[1;31mFailed to move build to releases directory\033[0m"; exit 1; }
-        echo -e "\033[1;32mBuild moved to $NEW_BUILD_DIR\033[0m"
+      run: mv temp "$NEW_BUILD_DIR"
 
-    - name: Update the symbolic link
-      working-directory: /var/www/collage.devtrend.tech
+    - name: Install SSH client
+      run: sudo apt-get install -y openssh-client
+
+    - name: Add SSH key
+      uses: webfactory/ssh-agent@v0.5.3
+      with:
+        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+
+    - name: Add remote server to known hosts
+      run: ssh-keyscan 146.190.199.118 >> ~/.ssh/known_hosts
+
+    - name: Transfer build to VPS
+      env:
+        NEW_BUILD_DIR: ${{ env.NEW_BUILD_DIR }}
+      run: scp -r $NEW_BUILD_DIR root@146.190.199.118:/var/www/collage.devtrend.tech/releases/
+
+    - name: Get the current release on VPS
       run: |
-        echo -e ">>> \033[1;34mUpdating symbolic link...\033[0m"
-        ln -sfn "$NEW_BUILD_DIR" .next || { 
-          echo -e "\033[1;31mFailed to update symbolic link\033[0m"; 
-          ln -sfn "$CURRENT_RELEASE" .next  # Revert to the old release
+        CURRENT_RELEASE=$(ssh root@146.190.199.118 "cd /var/www/collage.devtrend.tech && readlink .next") || CURRENT_RELEASE=".next"
+        echo "CURRENT_RELEASE=$CURRENT_RELEASE" >> $GITHUB_ENV
+
+    - name: Update the symbolic link on VPS
+      env:
+        NEW_BUILD_DIR: ${{ env.NEW_BUILD_DIR }}
+        CURRENT_RELEASE: ${{ env.CURRENT_RELEASE }}
+      run: |
+        ssh root@146.190.199.118 "cd /var/www/collage.devtrend.tech && ln -sfn /var/www/collage.devtrend.tech/$NEW_BUILD_DIR .next && echo 'Symbolic link updated to /var/www/collage.devtrend.tech/$NEW_BUILD_DIR' || { 
+          ln -sfn $CURRENT_RELEASE .next  # Revert to the old release
+          echo 'Failed to update symbolic link, reverted to $CURRENT_RELEASE'
           exit 1; 
-        }
-        echo -e "\033[1;32mRelease $NEW_BUILD_DIR staged successfully\033[0m"
+        }"
 
-    - name: Reload the pm2 process
-      working-directory: /var/www/collage.devtrend.tech
+    - name: Wait for 3 seconds
+      run: sleep 3
+
+    - name: Reload the pm2 process on VPS
+      env:
+        CURRENT_RELEASE: ${{ env.CURRENT_RELEASE }}
       run: |
-        echo -e ">>> \033[1;34mReloading the pm2 process...\033[0m"
-        PORT=3050 pm2 reload collage-devtrend-tech --update-env || { 
-          echo -e "\033[1;31mFailed to reload pm2 process\033[0m"; 
-          ln -sfn "$CURRENT_RELEASE" .next  # Revert to the old release
+        ssh root@146.190.199.118 "cd /var/www/collage.devtrend.tech && PORT=3050 pm2 reload collage-devtrend-tech --update-env || { 
+          ln -sfn $CURRENT_RELEASE .next  # Revert to the old release
           exit 1; 
-        }
-        echo -e "\033[1;32mPM2 process reloaded successfully\033[0m"
+        }"
 
-    - name: Check the number of releases and keep only 3 latest releases
-      working-directory: /var/www/collage.devtrend.tech
+    - name: Check the number of releases and keep only 3 latest releases on VPS
       run: |
-        RELEASES_COUNT=$(find releases -mindepth 1 -maxdepth 1 -type d | wc -l)
-        if [ "$RELEASES_COUNT" -gt 3 ]; then
-          echo -e ">>> \033[1;34mRemoving old releases...\033[0m"
-          find releases -mindepth 1 -maxdepth 1 -type d | sort | head -n -3 | xargs -I {} rm -rf {} || { echo -e "\033[1;31mFailed to remove old releases\033[0m"; exit 1; }
-          echo -e "\033[1;32mOld releases removed successfully\033[0m"
-        fi
-
-    - name: Deployment Status
-      if: always()
-      run: |
-        if [ "$?" -eq 0 ]; then
-          echo -e "\033[1;32mCollage site deployment completed successfully!\033[0m"
-        else
-          echo -e "\033[1;31mCollage site deployment failed!\033[0m"
-          exit 1
-        fi
-
-    - name: Restart the Runner
-      run: |
-        echo "sudo systemctl restart actions.runner.abdallah065-blog.nextjs-blog.service" | at now + 1 minute
+        ssh root@146.190.199.118 "cd /var/www/collage.devtrend.tech && RELEASES_COUNT=\$(find releases -mindepth 1 -maxdepth 1 -type d | wc -l || echo 0) &&
+        if [ \"\$RELEASES_COUNT\" -gt 3 ]; then
+          find releases -mindepth 1 -maxdepth 1 -type d | sort | head -n -3 | xargs -I {} rm -rf {}
+        fi"
